import './js/loader/loader';
import './js/loacal-storage/local-storage';
import './js/main.js/main-render';
import './js/dark/dark';
import './js/film.js/film-modal-window';
import './js/pagination/pagination';
import './js/upToTop/upToTop';
import './js/footer/team-modal-window';
import './js/watched-queue/watched-queue';
